version: "3"
services:
    web:
        build: .
        environment:
            - FLASK_ENV=development
        command: flask run --host 0.0.0.0
        volumes:
            - ./pdddf-service/:/app/
            - ./pdddf-data-uploads/:/uploads/

    worker:
        volumes:
            - ./pdddf-service/:/app/
            - ./pdddf-data-uploads/:/uploads/
            - ./pdddf-data-to-ocr/:/to-ocr/
            - ./pdddf-data-cache/:/root/.cache/
